### ISSUE TITLE
Option to repeat x times?

### ISSUE THREAD

**Issue by irrg** [n8henrie/homebridge-rcswitch-gpiomem#1]
Was curious if it'd be an option to repeat the signal a few times? I have a few outlets that aren't always getting the signal.

**Comment by n8henrie** [comment]
Sure. The original rcswitch code defaults to sending each code 10 times; I'll just expose its `setRepeatTransmit` method and allow users to increase it if desired.

**Comment by n8henrie** [comment]
Although note that the code changes will actually be in n8henrie/node-rcswitch-gpiomem; this repo will just have a minor configuration change.

**Comment by irrg** [comment]
You are the best.

**Comment by n8henrie** [comment]
Give it a shot and let me know if it helps. It seems to be working for me (takes significantly longer to return when `repeats` is 100 vs 10 and switches appropriately turn on and off), but I wasn't having a reliability problem in the first place, so it's hard to say for sure.

**Comment by irrg** [comment]
Sweet, just noticed the new NPM build, will try upgrading soon. I've got 1-2 of the etekcity outlets that are very bad at picking up the 'on'. Oddly enough their 'off' always comes through, so it's really unclear if repeats will help me here. But I figured it was worth a try!

**Comment by irrg** [comment]
I'm not going to jinx it, but I set repeat to 50 for the one picky outlet and so far success rate is greatly increased! More effect than adding a longer antenna, so I'll take it.

**Comment by n8henrie** [comment]
Good to hear!
