### ISSUE TITLE
Switch -> Lightbulb

### ISSUE THREAD

**Issue by jdtsmith** [n8henrie/homebridge-rcswitch-gpiomem#10]
This is working well to control Etekcity outlets all over the house (after I boosted my transmitter to 12V; see [this link](https://www.raspberrypi.org/forums/viewtopic.php?f=37&t=181618&p=1153964#p1153964).  

A trivial tweak suggestion: I added a config parameter "config.type" that can be "Lightbulb".  In this case, a Lightbulb instead of Switch service is created.  Not really different, except now I can say "Siri, turn off all my lights", and any RC-controlled lights are included.  Happy to send a PR if you are interested.

**Comment by n8henrie** [comment]
Sweet, please send the PR!

Nate

**Comment by jdtsmith** [comment]
I later realized this isn't at all necessary, since you can edit the detail for any switch and change its "Type" to Light (or Fan) in the Home app, which works just as well (and requires less code ;).

**Comment by n8henrie** [comment]
Gotcha, sweet.
