### ISSUE TITLE
not issue but request

### ISSUE THREAD

**Issue by toshibochan** [n8henrie/homebridge-rcswitch-gpiomem#4]
thanks for great homebridge. work great in my house. 
i have request if possible make other homebridge for receive not transmitter. i have some windows 433mhz sensors and 433mhz smoke detector and 433mhz motion detector. be great if i can receiver notification on homekit when Raspberry pi received signal from this RF sensors.

thanks again

**Comment by n8henrie** [comment]
I'm glad to hear this is working for you. Keep in mind that this is not homebridge itself, just a plugin. I don't think I'll be able to implement this feature myself, as I think it would require writing some kind of daemon that constantly listens (or stores and frequently polls) the 433 mhz receiver input. I don't know of a better way for the receiver to "notify" homebridge of an incoming signal.

If I come across a feasible way to implement this in rcswitch-gpiomem or if I come across another hombridge plugin that accomplishes it, I'll post it here, but in the meantime I'm going to close this issue. Feel free to give it a shot and send me a PR if you figure out a way.
