### ISSUE TITLE
increase RF Transmitter signal

### ISSUE THREAD

**Issue by toshibochan** [n8henrie/homebridge-rcswitch-gpiomem#5]
before my transmitter no reach all my outlets in my home. So i was reading my transmitter specification and say work in 5v to 12v, so i try 12v and now my transmitter reach all house, plus i connected 2 feet antenna to  the transmitter(2 feet because i have 2 feet of cable and i don't want cut).  If your transmitter work with 12v good to try. but do in your on risk.
transformer 12v + to transmitter +
transformer 12v - to transmitter - and to PI Ground

again do in your on risk if your transmitter work in 12v.

enjoy

**Comment by n8henrie** [comment]
That's great -- yes, my transmitter also supports up to 12v, but with a proper 1/4 wave antenna I have plenty of range to get consistent transmission around the house at 5v (especially with the repeat transmissions already built into the library, which you can increase as of https://github.com/n8henrie/homebridge-rcswitch-gpiomem/commit/02ea2fc26fa05a218b1caad9a05ace1c4eebb6ee).

Here are [some other suggestions](http://electronics.stackexchange.com/questions/132051/433mhz-quarter-wave-length-antenna-longer-is-better) for optimal antenna length for 433.

Closing this issue as it seems to be more of a suggestion than a problem.
