### ISSUE TITLE
Last Device in Scene not Working

### ISSUE THREAD

**Issue by quicklywilliam** [n8henrie/homebridge-rcswitch-gpiomem#9]
This issue seems similar to https://github.com/n8henrie/homebridge-rcswitch-gpiomem/issues/3, which was closed so I am filing a new one.

I am using homebridge 0.4.16 along with homebridge-rcswitch-gpiomem to control 5 RF switches. Individually the switches work fine. However, when I create a scene to toggle all 5 switches, the last one (the fifth one) fails to toggle. My guess here is that too much signal is being jammed through too fast, and that some kind of delay is necessary.

**Comment by quicklywilliam** [comment]
My mistake, I was using the wrong version – https://github.com/rainlake/homebridge-platform-rcswitch rather than this one. Once I switched over to homebridge-rcswitch-gpiomem it began working as expected!

**Comment by n8henrie** [comment]
Sweet! Glad to hear it.
